version: 2

builds:
  - main: ./main.go
    id: "gencli"
    binary: ./bin/gencli
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/lakshyajain-0291/gencli/pkg.Version={{ .Version }}
    ignore: 
      - goos: windows
      - goarch: arm64

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: gencli
    vendor: lakshyajain-0291
    homepage: https://github.com/lakshyajain-0291/gencli
    maintainer: Lakshya Jain <lakshyajainrj19@gmail.com>
    license: MIT
    formats:
      - deb
      - archlinux
      - rpm
    release: "1"
    bindir: /usr
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/gencli/LICENSE
      - src: README.md
        dst: /usr/share/doc/gencli/README.md
    
release:
  prerelease: auto
  github:
    owner: lakshyajain-0291
    name: gencli
  name_template: "{{.ProjectName}}-v{{.Version}}"

aurs:
  - name: gencli-bin
    homepage: https://github.com/lakshyajain-0291/gencli
    description: "GenCLI - A Gemini-Powered interactable CLI for fast, accurate file search."
    license: MIT
    maintainers:
      - "Lakshya Jain <lakshyajainrj19@gmail.com>"
    contributors:
      - "Lakshya Jain <lakshyajainrj19@gmail.com>"
    commit_author:
      name: lakshyajain-0291
      email: lakshyajainrj19@gmail.com
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/gencli-bin.git"
    package: |-
      install -Dm755 "./bin/gencli" "${pkgdir}/usr/bin/gencli"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gencli/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/gencli/README.md"

brews:
  - name: gencli
    url_template: "https://github.com/lakshyajain-0291/gencli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: lakshyajain-0291
      email: lakshyajainrj19@gmail.com
    commit_msg_template: "Brew formula update for gencli version {{ .Tag }}"
    homepage: "https://github.com/lakshyajain-0291/gencli"
    description: "GenCLI - A Gemini-Powered interactable CLI for fast, accurate file search."
    license: "MIT"
    skip_upload: false
    install: |
        bin.install "bin/gencli"
    repository:
      owner: lakshyajain-0291
      name: homebrew-gencli
      branch: main
      pull_request:
        enabled: false

archives:
  - format: zip
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    id: windows-archive

# scoops:
#   - name: gencli
#     url_template: "https://github.com/lakshyajain-0291/gencli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     commit_author:
#       name: lakshyajain-0291
#       email: lakshyajainrj19@gmail.com
#     commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
#     homepage: "https://github.com/lakshyajain-0291/gencli"
#     description: "GenCLI - A Gemini-Powered interactable CLI for fast, accurate file search."
#     license: MIT
#     skip_upload: false
#     repository:
#       owner: lakshyajain-0291
#       name: scoop-gencli
#       branch: main
#       pull_request:
#         enabled: false
